### ISSUE TITLE
Remove all references of vuejs syntax in the napps ui files

### ISSUE THREAD

**Issue by macartur** [kytos/ui#21]
Create new properties and methods to remove vuejs references. For example change `v-on:click.native` to a property named `on_click`.

- [ ] input
- [ ] base
- [ ] accordion
- [ ] property panel

**Comment by hdiogenes** [comment]
Currently, this is done with just one method (`on_click`) on just one component (`button`). This proposal also doesn't follow the same `camelCase` standard as other methods, so we're closing this for now.
