### ISSUE TITLE
Error when accessing UI with kytos 2019.2 rc

### ISSUE THREAD

**Issue by josemauro** [kytos/ui#57]
After download, install kytos from github (or pip), run 'kytos web update' command
 and try to run WEB UI the following  error messages is showed.
![Screenshot from 2019-12-18 11-49-50](https://user-images.githubusercontent.com/18131211/71096117-88a6eb00-218c-11ea-8053-da5ee84c867d.png)

**Comment by hdiogenes** [comment]
Did you run `kytos web update`?

**Comment by josemauro** [comment]
Yes and I update the comment to include this information. Thanks for asking.

**Comment by josemauro** [comment]
Well, It seems that the reason is that the latest.zip were not uploaded alongside with the source code of the last UI release (1.3.1) in https://github.com/kytos/ui/releases

**Comment by josemauro** [comment]
Well, It seems that the reason is that the latest.zip were not uploaded alongside with the source code of the last UI release (1.3.1) in https://github.com/kytos/ui/releases. The file were updated and the bug fixed.
