### ISSUE TITLE
Implement notification-item component for notifications tab

### ISSUE THREAD

**Issue by Niehaus** [kytos/ui#70]

**Comment by Niehaus** [comment]
A mockup preview of how the layout of the notification could be: a chosen icon by the user, title and description. What do you think @hdiogenes?

![Screenshot_2020-11-12 Kytos SDN Platform - Administrative Interface(1)](https://user-images.githubusercontent.com/17555995/98972162-d89f4680-24f0-11eb-869a-d498ae9936a0.png)

**Comment by Niehaus** [comment]
Notification with and without padding-left, which one is better? @hdiogenes @beraldoleal 

![Screenshot_2020-11-12 Kytos SDN Platform - Administrative Interface(2)](https://user-images.githubusercontent.com/17555995/98988006-c2e84c00-2505-11eb-9175-70a1613ccd50.png)

**Comment by beraldoleal** [comment]
I like the second one. Without.
